export type FilePreviewFormatGroup = {
  id: string
  label: string
  extensions: string[]
  note?: string
}

export type FilePreviewUnsupportedGroup = {
  label: string
  examples: string[]
  reason: string
}

/** 当前桌面端已接入的 @file-viewer 能力（lite + office + engineering + email） */
export const FILE_PREVIEW_SUPPORTED_GROUPS: FilePreviewFormatGroup[] = [
  {
    id: 'document',
    label: '文档与 Office',
    extensions: [
      'pdf',
      'ofd',
      'doc',
      'docx',
      'docm',
      'dot',
      'dotx',
      'dotm',
      'rtf',
      'odt',
      'odp',
      'xls',
      'xlsx',
      'xlsm',
      'xlsb',
      'xltx',
      'xlt',
      'xltm',
      'csv',
      'tsv',
      'ods',
      'fods',
      'numbers',
      'ppt',
      'pptx',
      'pptm',
      'potx',
      'potm',
      'ppsx',
      'ppsm',
    ],
    note: '复杂 Office 版式以浏览器端渲染为主，极端排版可能有偏差。',
  },
  {
    id: 'image',
    label: '图片',
    extensions: [
      'png',
      'jpg',
      'jpeg',
      'gif',
      'bmp',
      'tif',
      'tiff',
      'svg',
      'webp',
      'avif',
      'ico',
      'heic',
      'heif',
      'jxl',
    ],
  },
  {
    id: 'text',
    label: '文本与代码',
    extensions: [
      'txt',
      'md',
      'markdown',
      'json',
      'jsonc',
      'json5',
      'xml',
      'html',
      'htm',
      'css',
      'js',
      'mjs',
      'cjs',
      'ts',
      'tsx',
      'jsx',
      'vue',
      'py',
      'java',
      'go',
      'rs',
      'php',
      'rb',
      'swift',
      'kt',
      'c',
      'cpp',
      'cc',
      'h',
      'hpp',
      'cs',
      'sql',
      'sh',
      'bash',
      'yaml',
      'yml',
      'toml',
      'ini',
      'log',
      'diff',
      'patch',
      'bundle',
      'bdl',
      'ipynb',
      'proto',
      'hcl',
      'tex',
      'gv',
      'http',
      'react',
    ],
    note: '部分 .txt / .log / .ini 等会先经 Rust 侧识别 GBK/UTF-16 再预览。',
  },
  {
    id: 'media',
    label: '音频与视频',
    extensions: [
      'mp4',
      'webm',
      'm3u8',
      'mp3',
      'mpeg',
      'wav',
      'ogg',
      'oga',
      'opus',
      'm4a',
      'aac',
      'flac',
      'weba',
      'midi',
      'mid',
    ],
    note: '与视频播放器工具能力有重叠；此处仅做快速查看。',
  },
  {
    id: 'archive',
    label: '压缩包',
    extensions: [
      'zip',
      'zipx',
      '7z',
      'rar',
      'tar',
      'gz',
      'gzip',
      'tgz',
      'bz2',
      'bzip2',
      'tbz',
      'tbz2',
      'xz',
      'txz',
      'lzma',
      'zst',
      'tzst',
      'cab',
      'ar',
      'cpio',
      'iso',
      'xar',
      'lha',
      'lzh',
      'jar',
      'war',
      'ear',
      'apk',
      'cbz',
      'cbr',
    ],
    note: '支持浏览目录结构与包内文件预览；加密包需密码。',
  },
  {
    id: 'email',
    label: '邮件',
    extensions: ['eml', 'msg', 'mbox'],
  },
  {
    id: 'engineering',
    label: '工程 / CAD / 3D / 图纸',
    extensions: [
      'dwg',
      'dxf',
      'dwf',
      'dwfx',
      'xps',
      'glb',
      'gltf',
      'obj',
      'stl',
      'ply',
      'fbx',
      'dae',
      '3ds',
      '3mf',
      'amf',
      'usd',
      'usda',
      'usdc',
      'usdz',
      'kmz',
      'step',
      'stp',
      'iges',
      'igs',
      'ifc',
      '3dm',
      'brep',
      'pcd',
      'wrl',
      'vrml',
      'xyz',
      'vtk',
      'vtp',
      'excalidraw',
      'drawio',
      'dio',
      'mermaid',
      'mmd',
      'plantuml',
      'puml',
      'xmind',
      'geojson',
      'kml',
      'gpx',
      'shp',
      'typ',
      'typst',
      'olb',
      'dra',
      'gds',
      'oas',
      'oasis',
    ],
    note: 'CAD/3D 首次打开可能较慢，需加载 WASM/Worker 资源。',
  },
  {
    id: 'asset',
    label: '设计稿与数据资产',
    extensions: [
      'psd',
      'ai',
      'eps',
      'sqlite',
      'wasm',
      'parquet',
      'avro',
      'webarchive',
      'ttf',
      'otf',
      'woff',
      'woff2',
    ],
    note: 'PSD/AI 等为轻量预览或结构查看，非完整设计工具。',
  },
]

export const FILE_PREVIEW_UNSUPPORTED_GROUPS: FilePreviewUnsupportedGroup[] = [
  {
    label: '可执行与安装包',
    examples: ['exe', 'msi', 'dmg', 'pkg', 'deb', 'rpm', 'app', 'command'],
    reason: '安全原因不提供内联运行或安装界面，仅可下载。',
  },
  {
    label: '专有数据库 / 二进制',
    examples: ['db', 'mdb', 'accdb', 'frm', 'bin', 'dat', 'class'],
    reason: '未接入对应解析器；SQLite（.sqlite）已支持结构预览。',
  },
  {
    label: '电子书（未接入）',
    examples: ['epub', 'umd', 'mobi', 'azw3'],
    reason: '当前未安装 EPUB/UMD renderer，后续可按需扩展。',
  },
  {
    label: '音视频容器（未接入）',
    examples: ['mkv', 'avi', 'mov', 'flv', 'wmv', 'ts', 'm2ts'],
    reason: '部分格式请使用「视频播放器」工具；此处仅覆盖常见 mp4/webm 等。',
  },
  {
    label: '其他未识别扩展名',
    examples: ['任意未知后缀'],
    reason: '会出现在文件树中，预览区显示「不支持」并提供下载。',
  },
]

export const FILE_PREVIEW_SUPPORTED_EXTENSION_SET = new Set(
  FILE_PREVIEW_SUPPORTED_GROUPS.flatMap((group) => group.extensions),
)

export function isFilePreviewSupportedExtension(filename: string) {
  const extension = extractFileExtension(filename)
  return extension ? FILE_PREVIEW_SUPPORTED_EXTENSION_SET.has(extension) : false
}

export function extractFileExtension(filename: string) {
  const normalized = filename.trim().toLowerCase()
  if (!normalized.includes('.')) {
    return ''
  }

  return normalized.split('.').at(-1) ?? ''
}

export function countSupportedPreviewExtensions() {
  return FILE_PREVIEW_SUPPORTED_EXTENSION_SET.size
}
